//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Brightflow_mvc_opdracht.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }

        [Required(ErrorMessage = "Vul een naam in")]
        [StringLength(50), MinLength(3)]
        public string Product1 { get; set; } //ik weet wat hier mis mee is, het is niet zo erg, want ik gebruik het alleen voor de test
        public string ImagePath { get; set; }

        [Required(ErrorMessage = "Vul een prijs in")]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }
        public string Details { get; set; }
        public Nullable<int> Stock { get; set; }
    }
}
